2021_09/1

In [23]:
import numpy as np

In [101]:
with open('data/2021_09_test.txt') as f:
    data = f.read().splitlines()

for di, d in enumerate(data):
    data[di] = [11] + list(map(int,d)) + [11]

data = [[11]*len(data[0])] + data + [[11]*len(data[0])]
data = np.array(data)
data

array([[11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [11,  2,  1,  9,  9,  9,  4,  3,  2,  1,  0, 11],
       [11,  3,  9,  8,  7,  8,  9,  4,  9,  2,  1, 11],
       [11,  9,  8,  5,  6,  7,  8,  9,  8,  9,  2, 11],
       [11,  8,  7,  6,  7,  8,  9,  6,  7,  8,  9, 11],
       [11,  9,  8,  9,  9,  9,  6,  5,  6,  7,  8, 11],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11]])

In [102]:
res = []

for row in range(len(data)-2):
    for col in range(len(data[0])-2):
        
        window = data[row:row+3,col:col+3]
        
        center = window[1,1]
        nbs = min(window[0,1],window[1,0],window[1,2],window[2,1])
        
        if center < nbs:
            res.append(center)

result = sum(np.array(res)+1)

print('Result =', result) # 508

Result = 15


2021_09/2

In [103]:
data

array([[11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [11,  2,  1,  9,  9,  9,  4,  3,  2,  1,  0, 11],
       [11,  3,  9,  8,  7,  8,  9,  4,  9,  2,  1, 11],
       [11,  9,  8,  5,  6,  7,  8,  9,  8,  9,  2, 11],
       [11,  8,  7,  6,  7,  8,  9,  6,  7,  8,  9, 11],
       [11,  9,  8,  9,  9,  9,  6,  5,  6,  7,  8, 11],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11]])

In [201]:
pos = []

for row in range(len(data)-2):
    for col in range(len(data[0])-2):
        
        window = data[row:row+3,col:col+3]
        
        center = window[1,1]
        nbs = min(window[0,1],window[1,0],window[1,2],window[2,1])
        
        if center < nbs:
            pos.append([row+1,col+1])

pos

[[1, 2], [1, 10], [3, 3], [5, 7]]

In [235]:
p = pos[0]
# LOOP ''''''''''''''''''''''

s = []
for p in pos:

    low_in_row = list(np.where(data[p[0]] < 9)[0])
    low_in_row

    split = []
    for vi, value in enumerate(low_in_row[:-1]):
        if value + 1 == low_in_row[vi + 1]:
            split.append(value)
            split.append(value+1)          
        else:
            s.append(split)
            split =[]
            
print(s)

[[1, 2], [1, 2], [2, 3, 3, 4, 4, 5, 5, 6], [], []]


array([ 1,  2,  6,  7,  8,  9, 10], dtype=int64)